### ISSUE TITLE
previously Choice not show

### ISSUE THREAD

**Issue by JaofourthsOhappy** [tanasatit/ku-polls#52]
If a user selects a poll he already voted on, the list of choices shows which choice he/she previously selected. For example, a radio button is selected for his previous choice.
<img width="1728" alt="Screenshot 2567-09-15 at 10 33 13" src="https://github.com/user-attachments/assets/f4659de3-b81d-47ec-a82c-ee3f821535e8">

**Comment by tanasatit** [comment]
It has been fixed.
